# Pull Requestの変更に対応するラベルの定義
# https://github.com/actions/labeler
'Module:Core':
- changed-files:
  - any-glob-to-any-file: 'KarteCore/**'
'Module:CrashReport':
- changed-files:
  - any-glob-to-any-file: 'KarteCrashReporting/**'
'Module:IAM':
- changed-files:
  - any-glob-to-any-file: 'KarteInAppMessaging/**'
'Module:Notification':
- changed-files:
  - any-glob-to-any-file: 'KarteRemoteNotification/**'
'Module:Variables':
- changed-files:
  - any-glob-to-any-file: 'KarteVariables/**'
'Module:VT':
- changed-files:
  - any-glob-to-any-file: 'KarteVisualTracking/**'
'Module:Inbox':
- changed-files:
  - any-glob-to-any-file: 'KarteInbox/**'
'Module:IAF':
- changed-files:
  - any-glob-to-any-file: 'KarteInAppFrame/**'
'Module:Detectors':
- changed-files:
  - any-glob-to-any-file: 'KarteDetectors/**'
'Module:Utilities':
- changed-files:
  - any-glob-to-any-file: 'KarteUtilities/**'
'Module:NotificationServiceExtension':
- changed-files:
  - any-glob-to-any-file: 'KarteNotificationServiceExtension/**'
'Module:Debugger':
- changed-files:
  - any-glob-to-any-file: 'KarteDebugger/**'
'Test':
- changed-files:
  - any-glob-to-any-file: 'KarteTests/**'
