min_acl: public
clean: true
output: docs
author: PLAID, inc.
author_url: https://karte.io
readme: README.md
github_url: https://github.com/plaidev/karte-ios-sdk
skip_undocumented: true
hide_documentation_coverage: true
theme: apple
exclude:
  - KarteCore/Common/IdGenerator/*
  - KarteCore/Common/Module/*
  - KarteCore/Common/Library/*
  - KarteCore/Type/JSONConvertibleConverter.swift
  - KarteCore/Core/FindMyself/*
  - KarteCore/Core/Pv/*
  - KarteCore/Core/Scene/*
  - KarteCore/Core/AppInfo/*
  - KarteCore/Tracking/Client/*
  - KarteInAppMessaging/Preview/*
