name: "ghalint"
on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - develop
      - master
    paths:
      - '.github/workflows/**'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ghalint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.26'
      - name: Install ghalint
        run: go install github.com/suzuki-shunsuke/ghalint/cmd/ghalint@v1.5.5
      - name: Run ghalint
        run: ghalint run
