name: "Git-flow merge"
on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.repository != 'plaidev/karte-ios-sdk' && github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
    - name: Checkout develop
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Configure Git
      run: |
        git config user.email "git@users.noreply.github.com"
        git config user.name "github actions"
        git fetch
    - name: Checkout head branch
      run: |
        git checkout ${{ github.event.pull_request.head.sha }} -b ${{ github.head_ref }}
    - name: Merge to develop
      run: |
        git checkout develop
        git merge ${{ github.head_ref }} --no-ff -m "Merge ${{ github.head_ref }} into develop"
        git push
